function out = computeCOM(strideEvents, markerData, BW, slowleg, ...
    fastleg, impactS, expData, gaitEvents, flipIT)
%COMPUTECOM Compute stride-by-stride COM kinematics relative to each ankle.
%
%   Computes stride-by-stride COM position and velocity parameters in
% an ankle-centric reference frame. The body COM is estimated via
% appendBodyCOM if the BCOM marker is absent. The COM trajectory is
% rotated relative to each ankle, differentiated, low-pass filtered
% at 5 Hz, and time-normalized over the gait cycle. Per-stride
% values are extracted at heel strike and across mid-stance windows
% (indices 8-23 of the time-normalized trace). Symmetry parameters
% are computed as fast-minus-slow differences.
%
% Inputs:
%   strideEvents - struct of stride event times with fields tSHS,
%                  tFTO, tFHS, tSTO, tSHS2, tFTO2, tFHS2, tSTO2
%   markerData   - orientedLabTimeSeries of 3-D marker positions
%   BW           - participant body weight (kg)
%   slowleg      - slow-leg identifier, 'L' or 'R' (char)
%   fastleg      - fast-leg identifier, 'R' or 'L' (char)
%   impactS      - slow-leg impact force vector; length used for
%                  output row-count padding check (double)
%   expData      - experimentData object (unused; retained for
%                  call-site compatibility)
%   gaitEvents   - labTimeSeries of gait events for time-normalization
%   flipIT       - sign-flip scalar: +1 for level/incline,
%                  -1 for decline
%
% Outputs:
%   out - parameterSeries of COM position and velocity parameters
%         per stride (~72 parameters)
%
% Toolbox Dependencies:
%   None
%
% See also APPENDBODYCOM, COMPUTEFORCEPARAMETERS_OGFP, PARAMETERSERIES.

arguments
    strideEvents (1,1) struct
    markerData
    BW           (1,1) double
    slowleg      (1,:) char
    fastleg      (1,:) char
    impactS      (1,:) double
    expData
    gaitEvents
    flipIT       (1,1) double
end

%% Extract Stride Event Times
timeSHS  = strideEvents.tSHS;
timeFTO  = strideEvents.tFTO;
timeFHS  = strideEvents.tFHS;
timeSTO  = strideEvents.tSTO;
timeSHS2 = strideEvents.tSHS2;
timeFTO2 = strideEvents.tFTO2;
timeFHS2 = strideEvents.tFHS2;
timeSTO2 = strideEvents.tSTO2;
eventTimes = [timeSHS timeFTO timeFHS timeSTO ...
    timeSHS2 timeFTO2 timeFHS2 timeSTO2];
% numbers correspond to column of eventTimes matrix
SHS = 1; FTO = 2; FHS = 3; STO = 4;
SHS2 = 5; FTO2 = 6; FHS2 = 7; STO2 = 8;

%% Estimate Body COM if BCOM Marker Is Absent
% 2.) Convert to ankle centric reference frame.  (can use
% "getKinematicData" as a template as this converts everything into hip
% centered.
if isempty(markerData.getLabelsThatMatch('BCOM'))
    markerData = appendBodyCOM(markerData, 9.81*BW);
end
% animate(markerData);

%% Rotate Marker Data to Ankle-Centric Frames
% 3.) Rotate with respect to the ankle
rotatedMarkerData_F = getKinematicData_respect2Ank( ...
    markerData, {[fastleg, 'ANK']});
rotatedMarkerData_S = getKinematicData_respect2Ank( ...
    markerData, {[slowleg, 'ANK']});
% animate(rotatedMarkerData_F);

% ROTATED
COMTS_FANK = getDataAsTS( ...
    rotatedMarkerData_F, {'BCOMx' 'BCOMy' 'BCOMz'});
COMTS_SANK = getDataAsTS( ...
    rotatedMarkerData_S, {'BCOMx' 'BCOMy' 'BCOMz'});

%% Compute COM Velocity in Ankle-Centric Frame
% 4.) Aquire the speed of the COMTS in ankle specific CS for that ankles
% heel strike
T = length(timeSHS);

veloCOM_F_unfilteredY = ...
    COMTS_FANK.derivate.getDataAsTS({'d/dt BCOMy'});
veloCOM_S_unfilteredY = ...
    COMTS_SANK.derivate.getDataAsTS({'d/dt BCOMy'});
veloCOM_F_unfilteredZ = ...
    COMTS_FANK.derivate.getDataAsTS({'d/dt BCOMz'});
veloCOM_S_unfilteredZ = ...
    COMTS_SANK.derivate.getDataAsTS({'d/dt BCOMz'});

veloCOM_FY = veloCOM_F_unfilteredY.substituteNaNs.lowPassFilter(5);
veloCOM_SY = veloCOM_S_unfilteredY.substituteNaNs.lowPassFilter(5);
veloCOM_FZ = veloCOM_F_unfilteredZ.substituteNaNs.lowPassFilter(5);
veloCOM_SZ = veloCOM_S_unfilteredZ.substituteNaNs.lowPassFilter(5);

SHSTimer = nan(length(veloCOM_FY.Data), 1);
FHSTimer = nan(length(veloCOM_FY.Data), 1);

%% Time-Normalize COM Trajectories
%Time Normalied -- Rotated -- COM position
AlignedCOMTS_F = COMTS_FANK.align(gaitEvents, ...
    {[fastleg, 'HS'], [slowleg, 'TO'], ...
    [slowleg, 'HS'], [fastleg, 'TO']}, [15 30 15 40]);
AlignedCOMTS_S = COMTS_SANK.align(gaitEvents, ...
    {[slowleg, 'HS'], [fastleg, 'TO'], ...
    [fastleg, 'HS'], [slowleg, 'TO']}, [15 30 15 40]);
%Time Normalied -- Rotated -- COM velocity
AlignedCOMVelo_FY = veloCOM_FY.align(gaitEvents, ...
    {[fastleg, 'HS'], [slowleg, 'TO'], ...
    [slowleg, 'HS'], [fastleg, 'TO']}, [15 30 15 40]);
AlignedCOMVelo_SY = veloCOM_SY.align(gaitEvents, ...
    {[slowleg, 'HS'], [fastleg, 'TO'], ...
    [fastleg, 'HS'], [slowleg, 'TO']}, [15 30 15 40]);
AlignedCOMVelo_FZ = veloCOM_FZ.align(gaitEvents, ...
    {[fastleg, 'HS'], [slowleg, 'TO'], ...
    [slowleg, 'HS'], [fastleg, 'TO']}, [15 30 15 40]);
AlignedCOMVelo_SZ = veloCOM_SZ.align(gaitEvents, ...
    {[slowleg, 'HS'], [fastleg, 'TO'], ...
    [fastleg, 'HS'], [slowleg, 'TO']}, [15 30 15 40]);

%% Compute Per-Stride COM Parameters
for st = 1:T
    SHS = strideEvents.tSHS(st);
    FHS = strideEvents.tFHS(st);
    if ~isnan(SHS) && ~isnan(FHS)
        % Rotated at heel strike
        COMveloFY(st) = veloCOM_FY.Data( ...
            veloCOM_FY.getIndexClosestToTimePoint(FHS));
        COMveloSY(st) = veloCOM_SY.Data( ...
            veloCOM_SY.getIndexClosestToTimePoint(SHS));
        COMveloFZ(st) = veloCOM_FZ.Data( ...
            veloCOM_FZ.getIndexClosestToTimePoint(FHS));
        COMveloSZ(st) = veloCOM_SZ.Data( ...
            veloCOM_SZ.getIndexClosestToTimePoint(SHS));

        COMFY(st) = flipIT.*COMTS_FANK.Data( ...
            veloCOM_FY.getIndexClosestToTimePoint(FHS), 2);
        COMSY(st) = flipIT.*COMTS_SANK.Data( ...
            veloCOM_SY.getIndexClosestToTimePoint(SHS), 2);
        COMFZ(st) = flipIT.*COMTS_FANK.Data( ...
            veloCOM_FZ.getIndexClosestToTimePoint(FHS), 3);
        COMSZ(st) = flipIT.*COMTS_SANK.Data( ...
            veloCOM_SZ.getIndexClosestToTimePoint(SHS), 3);

        % Max/Min
        if T > 10 && st <= T-5
            % AVERAGE: Normalized, Rotated COM position and Velocity
            COMFY_Norm_Rot_mean(st) = flipIT.*mean( ...
                AlignedCOMTS_F.Data(8:23, 2, st), 'omitnan');
            COMSY_Norm_Rot_mean(st) = flipIT.*mean( ...
                AlignedCOMTS_S.Data(8:23, 2, st), 'omitnan');
            COMFZ_Norm_Rot_mean(st) = flipIT.*mean( ...
                AlignedCOMTS_F.Data(8:23, 3, st), 'omitnan');
            COMSZ_Norm_Rot_mean(st) = flipIT.*mean( ...
                AlignedCOMTS_S.Data(8:23, 3, st), 'omitnan');

            COMveloFY_Norm_Rot_mean(st) = flipIT.*mean( ...
                AlignedCOMVelo_FY.Data(8:23, 1, st), 'omitnan');
            COMveloSY_Norm_Rot_mean(st) = flipIT.*mean( ...
                AlignedCOMVelo_SY.Data(8:23, 1, st), 'omitnan');
            COMveloFZ_Norm_Rot_mean(st) = flipIT.*mean( ...
                AlignedCOMVelo_FZ.Data(8:23, 1, st), 'omitnan');
            COMveloSZ_Norm_Rot_mean(st) = flipIT.*mean( ...
                AlignedCOMVelo_SZ.Data(8:23, 1, st), 'omitnan');

            % AVERAGE: Normalized, Rotated COM position and Velocity
            COMFY_Norm_Rot_DSmean(st) = flipIT.*mean( ...
                AlignedCOMTS_F.Data(8:15, 2, st), 'omitnan');
            COMSY_Norm_Rot_DSmean(st) = flipIT.*mean( ...
                AlignedCOMTS_S.Data(8:15, 2, st), 'omitnan');
            COMFZ_Norm_Rot_DSmean(st) = flipIT.*mean( ...
                AlignedCOMTS_F.Data(8:15, 3, st), 'omitnan');
            COMSZ_Norm_Rot_DSmean(st) = flipIT.*mean( ...
                AlignedCOMTS_S.Data(8:15, 3, st), 'omitnan');

            % WHOLE AVERAGE: Normalized, Rotated COM pos. and Velocity
            COMFY_Norm_Rot_WHOLEmean(st) = flipIT.*mean( ...
                AlignedCOMTS_F.Data(:, 2, st), 'omitnan');
            COMSY_Norm_Rot_WHOLEmean(st) = flipIT.*mean( ...
                AlignedCOMTS_S.Data(:, 2, st), 'omitnan');
            COMFZ_Norm_Rot_WHOLEmean(st) = flipIT.*mean( ...
                AlignedCOMTS_F.Data(:, 3, st), 'omitnan');
            COMSZ_Norm_Rot_WHOLEmean(st) = flipIT.*mean( ...
                AlignedCOMTS_S.Data(:, 3, st), 'omitnan');

            COMveloFY_Norm_Rot_WHOLEmean(st) = flipIT.*mean( ...
                AlignedCOMVelo_FY.Data(:, 1, st), 'omitnan');
            COMveloSY_Norm_Rot_WHOLEmean(st) = flipIT.*mean( ...
                AlignedCOMVelo_SY.Data(:, 1, st), 'omitnan');
            COMveloFZ_Norm_Rot_WHOLEmean(st) = flipIT.*mean( ...
                AlignedCOMVelo_FZ.Data(:, 1, st), 'omitnan');
            COMveloSZ_Norm_Rot_WHOLEmean(st) = flipIT.*mean( ...
                AlignedCOMVelo_SZ.Data(:, 1, st), 'omitnan');

            % Little Bump Average: Normalized, Rotated COM pos. and Velocity
            COMFZ_Norm_Rot_Retraction(st) = flipIT.*min( ...
                AlignedCOMTS_F.Data(90:100, 3, st), [], 'omitnan');
            COMSZ_Norm_Rot_Retraction(st) = flipIT.*min( ...
                AlignedCOMTS_S.Data(90:100, 3, st), [], 'omitnan');
            COMveloFZ_Norm_Rot_Retraction(st) = flipIT.*min( ...
                AlignedCOMVelo_FZ.Data(90:100, 1, st), [], 'omitnan');
            COMveloSZ_Norm_Rot_Retraction(st) = flipIT.*min( ...
                AlignedCOMVelo_SZ.Data(90:100, 1, st), [], 'omitnan');

            %Time Normalied -- Rotated -- COM position and Velocity
            [COMFY_Norm_Rot_max(st), COMFY_Norm_Rot_maxIndex(st)] = ...
                max(flipIT.*AlignedCOMTS_F.Data(:, 2, st), [], 'omitnan');
            [COMSY_Norm_Rot_max(st), COMSY_Norm_Rot_maxIndex(st)] = ...
                max(flipIT.*AlignedCOMTS_S.Data(:, 2, st), [], 'omitnan');
            [COMFY_Norm_Rot_min(st), COMFY_Norm_Rot_minIndex(st)] = ...
                min(flipIT.*AlignedCOMTS_F.Data(:, 2, st), [], 'omitnan');
            [COMSY_Norm_Rot_min(st), COMSY_Norm_Rot_minIndex(st)] = ...
                min(flipIT.*AlignedCOMTS_S.Data(:, 2, st), [], 'omitnan');

            [COMFZ_Norm_Rot_max(st), COMFZ_Norm_Rot_maxIndex(st)] = ...
                max(AlignedCOMTS_F.Data(:, 3, st), [], 'omitnan');
            [COMSZ_Norm_Rot_max(st), COMSZ_Norm_Rot_maxIndex(st)] = ...
                max(AlignedCOMTS_S.Data(:, 3, st), [], 'omitnan');
            [COMFZ_Norm_Rot_min(st), COMFZ_Norm_Rot_minIndex(st)] = ...
                min(AlignedCOMTS_F.Data(:, 3, st), [], 'omitnan');
            [COMSZ_Norm_Rot_min(st), COMSZ_Norm_Rot_minIndex(st)] = ...
                min(AlignedCOMTS_S.Data(:, 3, st), [], 'omitnan');

            [COMveloFY_Norm_Rot_max(st), ...
                COMveloFY_Norm_Rot_maxIndex(st)] = ...
                max(flipIT.*AlignedCOMVelo_FY.Data(:, 1, st), [], 'omitnan');
            [COMveloSY_Norm_Rot_max(st), ...
                COMveloSY_Norm_Rot_maxIndex(st)] = ...
                max(flipIT.*AlignedCOMVelo_SY.Data(:, 1, st), [], 'omitnan');
            [COMveloFY_Norm_Rot_min(st), ...
                COMveloFY_Norm_Rot_minIndex(st)] = ...
                min(flipIT.*AlignedCOMVelo_FY.Data(:, 1, st), [], 'omitnan');
            [COMveloSY_Norm_Rot_min(st), ...
                COMveloSY_Norm_Rot_minIndex(st)] = ...
                min(flipIT.*AlignedCOMVelo_SY.Data(:, 1, st), [], 'omitnan');

            [COMveloFZ_Norm_Rot_max(st), ...
                COMveloFZ_Norm_Rot_maxIndex(st)] = ...
                max(AlignedCOMVelo_FZ.Data(:, 1, st), [], 'omitnan');
            [COMveloSZ_Norm_Rot_max(st), ...
                COMveloSZ_Norm_Rot_maxIndex(st)] = ...
                max(AlignedCOMVelo_SZ.Data(:, 1, st), [], 'omitnan');
            [COMveloFZ_Norm_Rot_min(st), ...
                COMveloFZ_Norm_Rot_minIndex(st)] = ...
                min(AlignedCOMVelo_FZ.Data(:, 1, st), [], 'omitnan');
            [COMveloSZ_Norm_Rot_min(st), ...
                COMveloSZ_Norm_Rot_minIndex(st)] = ...
                min(AlignedCOMVelo_SZ.Data(:, 1, st), [], 'omitnan');

        else
            COMFZ_Norm_Rot_minIndex(st) = NaN;
            COMSZ_Norm_Rot_minIndex(st) = NaN;

            % AVERAGE: Normalized, Rotated COM position and Velocity
            COMFY_Norm_Rot_mean(st) = NaN;
            COMSY_Norm_Rot_mean(st) = NaN;
            COMFZ_Norm_Rot_mean(st) = NaN;
            COMSZ_Norm_Rot_mean(st) = NaN;

            COMveloFY_Norm_Rot_mean(st) = NaN;
            COMveloSY_Norm_Rot_mean(st) = NaN;
            COMveloFZ_Norm_Rot_mean(st) = NaN;
            COMveloSZ_Norm_Rot_mean(st) = NaN;

            COMFY_Norm_Rot_DSmean(st) = NaN;
            COMSY_Norm_Rot_DSmean(st) = NaN;
            COMFZ_Norm_Rot_DSmean(st) = NaN;
            COMSZ_Norm_Rot_DSmean(st) = NaN;

            COMFY_Norm_Rot_WHOLEmean(st) = NaN;
            COMSY_Norm_Rot_WHOLEmean(st) = NaN;
            COMFZ_Norm_Rot_WHOLEmean(st) = NaN;
            COMSZ_Norm_Rot_WHOLEmean(st) = NaN;

            COMveloFY_Norm_Rot_WHOLEmean(st) = NaN;
            COMveloSY_Norm_Rot_WHOLEmean(st) = NaN;
            COMveloFZ_Norm_Rot_WHOLEmean(st) = NaN;
            COMveloSZ_Norm_Rot_WHOLEmean(st) = NaN;

            % Little Bump Average: Normalized, Rotated COM pos. and Velocity
            COMFZ_Norm_Rot_Retraction(st)     = NaN;
            COMSZ_Norm_Rot_Retraction(st)     = NaN;
            COMveloFZ_Norm_Rot_Retraction(st) = NaN;
            COMveloSZ_Norm_Rot_Retraction(st) = NaN;

            %Time Normalied -- Rotated -- COM position and Velocity
            COMFY_Norm_Rot_max(st)      = NaN;
            COMFY_Norm_Rot_maxIndex(st) = NaN;
            COMSY_Norm_Rot_max(st)      = NaN;
            COMSY_Norm_Rot_maxIndex(st) = NaN;
            COMFY_Norm_Rot_min(st)      = NaN;
            COMFY_Norm_Rot_minIndex(st) = NaN;
            COMSY_Norm_Rot_min(st)      = NaN;
            COMSY_Norm_Rot_minIndex(st) = NaN;

            COMFZ_Norm_Rot_max(st)      = NaN;
            COMFZ_Norm_Rot_maxIndex(st) = NaN;
            COMSZ_Norm_Rot_max(st)      = NaN;
            COMSZ_Norm_Rot_maxIndex(st) = NaN;
            COMFZ_Norm_Rot_min(st)      = NaN;
            COMFZ_Norm_Rot_minIndex(st) = NaN;
            COMSZ_Norm_Rot_min(st)      = NaN;
            COMSZ_Norm_Rot_minIndex(st) = NaN;

            COMveloFY_Norm_Rot_max(st)      = NaN;
            COMveloFY_Norm_Rot_maxIndex(st) = NaN;
            COMveloSY_Norm_Rot_max(st)      = NaN;
            COMveloSY_Norm_Rot_maxIndex(st) = NaN;
            COMveloFY_Norm_Rot_min(st)      = NaN;
            COMveloFY_Norm_Rot_minIndex(st) = NaN;
            COMveloSY_Norm_Rot_min(st)      = NaN;
            COMveloSY_Norm_Rot_minIndex(st) = NaN;

            COMveloFZ_Norm_Rot_max(st)      = NaN;
            COMveloFZ_Norm_Rot_maxIndex(st) = NaN;
            COMveloSZ_Norm_Rot_max(st)      = NaN;
            COMveloSZ_Norm_Rot_maxIndex(st) = NaN;
            COMveloFZ_Norm_Rot_min(st)      = NaN;
            COMveloFZ_Norm_Rot_minIndex(st) = NaN;
            COMveloSZ_Norm_Rot_min(st)      = NaN;
            COMveloSZ_Norm_Rot_minIndex(st) = NaN;
        end
    end
    clear tempFHS tempSHS
end

%% Compute Symmetry Parameters
COMveloY = COMveloFY - COMveloSY;
COMveloZ = COMveloFZ - COMveloSZ;

COMY = COMFY - COMSY;
COMZ = COMFZ - COMSZ;

COMsymY_Norm_Rot_mean = COMFY_Norm_Rot_mean - COMSY_Norm_Rot_mean;
COMsymZ_Norm_Rot_mean = COMFZ_Norm_Rot_mean - COMSZ_Norm_Rot_mean;
COMveloSYMY_Norm_Rot_mean = ...
    COMveloFY_Norm_Rot_mean - COMveloSY_Norm_Rot_mean;
COMveloSYMZ_Norm_Rot_mean = ...
    COMveloFZ_Norm_Rot_mean - COMveloSZ_Norm_Rot_mean;

COMsymY_Norm_Rot_DSmean = ...
    COMFY_Norm_Rot_DSmean - COMSY_Norm_Rot_DSmean;
COMsymZ_Norm_Rot_DSmean = ...
    COMFZ_Norm_Rot_DSmean - COMSZ_Norm_Rot_DSmean;

COMsymY_Norm_Rot_WHOLEmean = ...
    COMFY_Norm_Rot_WHOLEmean - COMSY_Norm_Rot_WHOLEmean;
COMsymZ_Norm_Rot_WHOLEmean = ...
    COMFZ_Norm_Rot_WHOLEmean - COMSZ_Norm_Rot_WHOLEmean;
COMveloSymY_Norm_Rot_WHOLEmean = ...
    COMveloFY_Norm_Rot_WHOLEmean - COMveloSY_Norm_Rot_WHOLEmean;
COMveloSymZ_Norm_Rot_WHOLEmean = ...
    COMveloFZ_Norm_Rot_WHOLEmean - COMveloSZ_Norm_Rot_WHOLEmean;

% Time Normalied -- Rotated -- COM position and Velocity
COMsymY_Norm_Rot_max = COMFY_Norm_Rot_max - COMSY_Norm_Rot_max;
COMsymY_Norm_Rot_min = COMFY_Norm_Rot_min - COMSY_Norm_Rot_min;
COMsymZ_Norm_Rot_max = COMFZ_Norm_Rot_max - COMSZ_Norm_Rot_max;
COMsymZ_Norm_Rot_min = COMFZ_Norm_Rot_min - COMSZ_Norm_Rot_min;

COMveloSYMY_Norm_Rot_max = ...
    COMveloFY_Norm_Rot_max - COMveloSY_Norm_Rot_max;
COMveloSYMY_Norm_Rot_min = ...
    COMveloFY_Norm_Rot_min - COMveloSY_Norm_Rot_min;
COMveloSYMZ_Norm_Rot_max = ...
    COMveloFZ_Norm_Rot_max - COMveloSZ_Norm_Rot_max;
COMveloSYMZ_Norm_Rot_min = ...
    COMveloFZ_Norm_Rot_min - COMveloSZ_Norm_Rot_min;

%% Assemble Output Data Matrix
data = [COMveloY' COMveloFY' COMveloSY' COMveloZ' ...
    COMveloFZ' COMveloSZ' ...
    COMY' COMFY' COMSY' COMZ' COMFZ' COMSZ' ...
    COMsymY_Norm_Rot_mean' COMFY_Norm_Rot_mean' ...
    COMSY_Norm_Rot_mean' ...
    COMsymZ_Norm_Rot_mean' COMFZ_Norm_Rot_mean' ...
    COMSZ_Norm_Rot_mean' ...
    COMveloSYMY_Norm_Rot_mean' COMveloFY_Norm_Rot_mean' ...
    COMveloSY_Norm_Rot_mean' ...
    COMveloSYMZ_Norm_Rot_mean' COMveloFZ_Norm_Rot_mean' ...
    COMveloSZ_Norm_Rot_mean' ...
    COMsymY_Norm_Rot_DSmean' COMFY_Norm_Rot_DSmean' ...
    COMSY_Norm_Rot_DSmean' ...
    COMsymZ_Norm_Rot_DSmean' COMFZ_Norm_Rot_DSmean' ...
    COMSZ_Norm_Rot_DSmean' ...
    COMsymY_Norm_Rot_WHOLEmean' COMFY_Norm_Rot_WHOLEmean' ...
    COMSY_Norm_Rot_WHOLEmean' ...
    COMsymZ_Norm_Rot_WHOLEmean' COMFZ_Norm_Rot_WHOLEmean' ...
    COMSZ_Norm_Rot_WHOLEmean' ...
    COMveloSymY_Norm_Rot_WHOLEmean' ...
    COMveloFY_Norm_Rot_WHOLEmean' ...
    COMveloSY_Norm_Rot_WHOLEmean' ...
    COMveloSymZ_Norm_Rot_WHOLEmean' ...
    COMveloFZ_Norm_Rot_WHOLEmean' ...
    COMveloSZ_Norm_Rot_WHOLEmean' ...
    COMFZ_Norm_Rot_minIndex' COMSZ_Norm_Rot_minIndex' ...
    COMFZ_Norm_Rot_Retraction' COMSZ_Norm_Rot_Retraction' ...
    COMveloFZ_Norm_Rot_Retraction' COMveloSZ_Norm_Rot_Retraction' ...
    COMsymY_Norm_Rot_max' COMFY_Norm_Rot_max' ...
    COMSY_Norm_Rot_max' ... %% Normalized, Rotated COM pos. and Velocity
    COMsymY_Norm_Rot_min' COMFY_Norm_Rot_min' ...
    COMSY_Norm_Rot_min' ...
    COMsymZ_Norm_Rot_max' COMFZ_Norm_Rot_max' ...
    COMSZ_Norm_Rot_max' ...
    COMsymZ_Norm_Rot_min' COMFZ_Norm_Rot_min' ...
    COMSZ_Norm_Rot_min' ...
    COMveloSYMY_Norm_Rot_max' COMveloFY_Norm_Rot_max' ...
    COMveloSY_Norm_Rot_max' ...
    COMveloSYMY_Norm_Rot_min' COMveloFY_Norm_Rot_min' ...
    COMveloSY_Norm_Rot_min' ...
    COMveloSYMZ_Norm_Rot_max' COMveloFZ_Norm_Rot_max' ...
    COMveloSZ_Norm_Rot_max' ...
    COMveloSYMZ_Norm_Rot_min' COMveloFZ_Norm_Rot_min' ...
    COMveloSZ_Norm_Rot_min'];

labels = {'COMveloY' 'COMveloFY' 'COMveloSY' 'COMveloZ' ...
    'COMveloFZ' 'COMveloSZ' ...
    'COMY' 'COMFY' 'COMSY' 'COMZ' 'COMFZ' 'COMSZ' ...
    'COMsymY_Norm_Rot_mean' 'COMFY_Norm_Rot_mean' ...
    'COMSY_Norm_Rot_mean' ...
    'COMsymZ_Norm_Rot_mean' 'COMFZ_Norm_Rot_mean' ...
    'COMSZ_Norm_Rot_mean' ...
    'COMveloSYMY_Norm_Rot_mean' 'COMveloFY_Norm_Rot_mean' ...
    'COMveloSY_Norm_Rot_mean' ...
    'COMveloSYMZ_Norm_Rot_mean' 'COMveloFZ_Norm_Rot_mean' ...
    'COMveloSZ_Norm_Rot_mean' ...
    'COMsymY_Norm_Rot_DSmean' 'COMFY_Norm_Rot_DSmean' ...
    'COMSY_Norm_Rot_DSmean' ...
    'COMsymZ_Norm_Rot_DSmean' 'COMFZ_Norm_Rot_DSmean' ...
    'COMSZ_Norm_Rot_DSmean' ...
    'COMsymY_Norm_Rot_WHOLEmean' 'COMFY_Norm_Rot_WHOLEmean' ...
    'COMSY_Norm_Rot_WHOLEmean' ...
    'COMsymZ_Norm_Rot_WHOLEmea' 'COMFZ_Norm_Rot_WHOLEmean' ...
    'COMSZ_Norm_Rot_WHOLEmean' ...
    'COMveloSymY_Norm_Rot_WHOLEmean' ...
    'COMveloFY_Norm_Rot_WHOLEmean' ...
    'COMveloSY_Norm_Rot_WHOLEmean' ...
    'COMveloSymZ_Norm_Rot_WHOLEmean' ...
    'COMveloFZ_Norm_Rot_WHOLEmean' ...
    'COMveloSZ_Norm_Rot_WHOLEmean' ...
    'COMFZ_Norm_Rot_minIndex' 'COMSZ_Norm_Rot_minIndex' ...
    'COMFZ_Norm_Rot_Retraction' 'COMSZ_Norm_Rot_Retraction' ...
    'COMveloFZ_Norm_Rot_Retraction' 'COMveloSZ_Norm_Rot_Retraction' ...
    'COMsymY_Norm_Rot_max' 'COMFY_Norm_Rot_max' ...
    'COMSY_Norm_Rot_max' ... %% Normalized, Rotated COM pos. and Velocity
    'COMsymY_Norm_Rot_min' 'COMFY_Norm_Rot_min' ...
    'COMSY_Norm_Rot_min' ...
    'COMsymZ_Norm_Rot_max' 'COMFZ_Norm_Rot_max' ...
    'COMSZ_Norm_Rot_max' ...
    'COMsymZ_Norm_Rot_min' 'COMFZ_Norm_Rot_min' ...
    'COMSZ_Norm_Rot_min' ...
    'COMveloSYMY_Norm_Rot_max' 'COMveloFY_Norm_Rot_max' ...
    'COMveloSY_Norm_Rot_max' ...
    'COMveloSYMY_Norm_Rot_min' 'COMveloFY_Norm_Rot_min' ...
    'COMveloSY_Norm_Rot_min' ...
    'COMveloSYMZ_Norm_Rot_max' 'COMveloFZ_Norm_Rot_max' ...
    'COMveloSZ_Norm_Rot_max' ...
    'COMveloSYMZ_Norm_Rot_min' 'COMveloFZ_Norm_Rot_min' ...
    'COMveloSZ_Norm_Rot_min'};

%% Return Output
if length(impactS) == length(COMveloFY)
    data = [data; NaN(1, size(data, 2))];
end
description = cell(1, size(data, 2));
description(:) = {''};
out = parameterSeries(data, labels, [], description);

end

