%CREATEDEPENDENTPARAMRECIPES Build and save dependent parameter recipes.
%
%   Creates a recipe table (fieldList) defining how derived EMG
% parameters are computed from base stride-segment parameters. The
% table includes a hip contribution entry and phase-average (p),
% time-integrated (t), and stride-normalized (e) versions of each
% EMG muscle/side combination. The completed table is saved as
% DependParamRecipes.mat in the same directory as this script.
%
% Toolbox Dependencies:
%   None
%
% See also ADAPTATIONDATA, CALCPARAMETERS.

%% Initialize Recipe List
fieldList = {'hipContribution', '@(w,x,y,z) w-x-y-z', ...
    {'netContributionNorm2', 'spatialContributionNorm2', ...
    'stepTimeContributionPNorm', 'velocityContributionPNorm'}, ...
    'computes the proposed hip contrib'};

%% Add Derived EMG Parameters
muscleList = {'TA', 'PER', 'MG', 'LG', 'SOL', 'RF', 'VM', 'VF', ...
    'SEMT', 'SEMB', 'BF', 'GLU', 'TFL', 'HIP', 'ADM'};
% Going from 's' to 'p' parameters is equivalent to averaging each
% pair of 's' parameters into a single value. For each muscle, this
% is equivalent to multiplying by the matrix:
%   s2pMatrix = nan(12, 6);
%   s2pMatrix([1:2:12, 2:2:12], :) = .5*[eye(6) eye(6)]';
sides = {'R', 'L'};
desc = {'SHS to FTO', 'FTO to mid fast swing', ...
    'mid fast swing to FHS', 'FHS to STO', ...
    'STO to mid slow swing', 'mid slow swing to SHS'};
timeScaleParam = {'doubleSupportTemp', 'doubleSupportTemp', ...
    'swingTimeFast',     'swingTimeFast', ...
    'swingTimeFast',     'swingTimeFast', ...
    'doubleSupportSlow', 'doubleSupportSlow', ...
    'swingTimeSlow',     'swingTimeSlow', ...
    'swingTimeSlow',     'swingTimeSlow'};
timeScaleK = [2, 2, 1, 1, 1, 1, 2, 2, 1, 1, 1, 1];
for iSide = 1:2
    side = sides{iSide};
    for iMuscle = 1:length(muscleList)
        for iParam = 1:6  % phase-average (p) parameters
            fieldList(end+1, :) = { ...
                [side muscleList{iMuscle} 'p' num2str(iParam)], ...
                '@(x,y) .5*(x+y)', ...
                {[side muscleList{iMuscle} 's' num2str(2*iParam - 1)], ...
                [side muscleList{iMuscle} 's' num2str(2*iParam)]}, ...
                ['Average of proc EMG data in muscle ' ...
                side muscleList{iMuscle} ' from ' desc{iParam}]};
        end
        for iParam = 1:12  % time-integrated (t) parameters
            fieldList(end+1, :) = { ...
                [side muscleList{iMuscle} 't' num2str(iParam)], ...
                ['@(x,y) .25*x.*y*' num2str(timeScaleK(iParam))], ...
                {[side muscleList{iMuscle} 's' num2str(iParam)], ...
                timeScaleParam{iParam}}, ...
                ['Integrated (instead of averaged) version of ' ...
                side muscleList{iMuscle} 's' num2str(iParam)]};
        end
        for iParam = 1:12  % stride-normalized (e) parameters
            fieldList(end+1, :) = { ...
                [side muscleList{iMuscle} 'e' num2str(iParam)], ...
                '@(x,y) x./y', ...
                {[side muscleList{iMuscle} 't' num2str(iParam)], ...
                'strideTimeSlow'}, ...
                ['Time normalize (by stride cycle duration) version of ' ...
                side muscleList{iMuscle} 't' num2str(iParam)]};
        end
    end
end

%% Save Recipe File
scriptFullPath = mfilename('fullpath');
scriptName     = mfilename;
pathParts      = regexp(scriptFullPath, scriptName, 'split');
save([pathParts{1} 'DependParamRecipes.mat'], 'fieldList')

